Repository ThomasRempel/tinder-politecnica, pull requests merged in 2021-11, with the labels that each got.

#5 Developer
  .idea/misc.xml
  .idea/uiDesigner.xml
  out/production/tinder-politecnica/controlador/Controlador.class
  out/production/tinder-politecnica/modelo/Usuario.class
  out/production/tinder-politecnica/principal/Principal.class
  out/production/tinder-politecnica/principal/UI.class
  src/Usuario.java
  src/controlador/Controlador.java
  src/modelo/Usuario.java
  src/principal/Principal.java
  src/principal/UI.java
Labels: documentation, enhancement

#11 Merge com Developer
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/runConfigurations.xml
  README.md
  out/production/tinder-politecnica/controlador/Controlador.class
  out/production/tinder-politecnica/controlador/ControladorTxt.class
  out/production/tinder-politecnica/modelo/UsuariaMulher.class
  out/production/tinder-politecnica/modelo/Usuario.class
  out/production/tinder-politecnica/modelo/UsuarioHomem.class
  out/production/tinder-politecnica/principal/Principal.class
  out/production/tinder-politecnica/principal/UI.class
  perfis.txt
  perfisMasc.txt
  src/controlador/Controlador.java
  src/controlador/ControladorTxt.java
  src/modelo/UsuariaMulher.java
  src/modelo/Usuario.java
  src/modelo/UsuarioHomem.java
  src/principal/Principal.java
  src/principal/UI.java
Labels: enhancement, good first issue

#12 Developer
  out/production/tinder-politecnica/controlador/Controlador.class
  out/production/tinder-politecnica/controlador/ControladorTxt.class
  out/production/tinder-politecnica/modelo/Usuario.class
  out/production/tinder-politecnica/principal/Principal.class
  out/production/tinder-politecnica/principal/UI.class
  out/production/tinder-politecnica/utils/DadosTxt.class
  perfis.txt
  perfisFem.txt
  perfisMasc.txt
  src/controlador/Controlador.java
  src/controlador/ControladorTxt.java
  src/principal/Principal.java
  src/utils/DadosTxt.java
Labels: enhancement

#14 Developer
  .idea/misc.xml
  out/production/tinder-politecnica/controlador/Controlador.class
  out/production/tinder-politecnica/controlador/ControladorTxt.class
  out/production/tinder-politecnica/modelo/Usuario.class
  out/production/tinder-politecnica/principal/UI.class
  src/controlador/Controlador.java
  src/controlador/ControladorTxt.java
  src/modelo/Usuario.java
  src/principal/UI.java
  src/utils/DadosTxt.java
Labels: enhancement

#24 Developer
  .idea/misc.xml
  out/production/tinder-politecnica/controlador/Controlador.class
  out/production/tinder-politecnica/controlador/ControladorTxt.class
  out/production/tinder-politecnica/exception/ExcecaoCaracter.class
  out/production/tinder-politecnica/exception/ExcecaoNumero.class
  out/production/tinder-politecnica/modelo/UsuariaMulher.class
  out/production/tinder-politecnica/modelo/Usuario.class
  out/production/tinder-politecnica/modelo/UsuarioHomem.class
  out/production/tinder-politecnica/principal/Principal.class
  out/production/tinder-politecnica/principal/UI.class
  out/production/tinder-politecnica/utils/DadosTxt.class
  src/controlador/Controlador.java
  src/controlador/ControladorTxt.java
  src/exception/ExcecaoCaracter.java
  src/exception/ExcecaoNumero.java
  src/modelo/Usuario.java
  src/principal/Principal.java
  src/principal/UI.java
Labels: enhancement, código
